# Generated by Django 3.2.8 on 2021-10-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('lat', models.FloatField(max_length=500)),
                ('lon', models.FloatField(max_length=500)),
                ('state', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
