# Generated by Django 2.2 on 2021-10-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211016_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=500)),
                ('manufacturer', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('fare_price', models.FloatField(max_length=500)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_aircraft', to='core.Aircraft')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('currency', models.CharField(max_length=500)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_destination', to='core.Airport')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Itinerary')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_origin', to='core.Airport')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
