# Generated by Django 2.2 on 2021-10-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_suitable'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='duration_h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='fare_by_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='velocity_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
