# Generated by Django 2.2 on 2021-10-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211018_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
