# Generated by Django 2.2 on 2021-10-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_travel_distance_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='departure_date',
            field=models.DateTimeField(),
        ),
    ]
