# Generated by Django 2.2 on 2021-10-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211020_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='dist',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
